/**
 * Init Command
 *
 * Initializes a new Conductor installation.
 */

import { writeFile, mkdir, access } from 'fs/promises';
import { join } from 'path';
import chalk from 'chalk';
import inquirer from 'inquirer';
import ora from 'ora';

interface InitOptions {
  dir: string;
}

export async function initCommand(options: InitOptions): Promise<void> {
  console.log(chalk.blue.bold('\n🎵 Conductor Setup\n'));

  const targetDir = options.dir === '.' ? process.cwd() : options.dir;

  // Check if already initialized
  const envExists = await access(join(targetDir, '.env'))
    .then(() => true)
    .catch(() => false);

  if (envExists) {
    const { overwrite } = await inquirer.prompt([
      {
        type: 'confirm',
        name: 'overwrite',
        message: 'A .env file already exists. Do you want to reconfigure?',
        default: false,
      },
    ]);

    if (!overwrite) {
      console.log(chalk.yellow('Setup cancelled.'));
      return;
    }
  }

  // Gather configuration
  const answers = await inquirer.prompt([
    {
      type: 'input',
      name: 'githubAppId',
      message: 'GitHub App ID:',
      validate: (input: string) => input.length > 0 || 'GitHub App ID is required',
    },
    {
      type: 'input',
      name: 'githubPrivateKeyPath',
      message: 'Path to GitHub App private key (.pem file):',
      default: './secrets/github-app.pem',
    },
    {
      type: 'input',
      name: 'githubWebhookSecret',
      message: 'GitHub Webhook Secret:',
      default: 'conductor-webhook-secret-123',
    },
    {
      type: 'input',
      name: 'databaseUrl',
      message: 'PostgreSQL Database URL:',
      default: 'postgres://conductor:conductor@localhost:5432/conductor',
    },
    {
      type: 'input',
      name: 'redisUrl',
      message: 'Redis URL:',
      default: 'redis://localhost:6379',
    },
    {
      type: 'input',
      name: 'port',
      message: 'Webhook server port:',
      default: '3000',
    },
    {
      type: 'confirm',
      name: 'enableTelegram',
      message: 'Enable Telegram notifications?',
      default: false,
    },
  ]);

  let telegramConfig = {};
  if (answers.enableTelegram) {
    const telegramAnswers = await inquirer.prompt([
      {
        type: 'input',
        name: 'telegramBotToken',
        message: 'Telegram Bot Token:',
      },
      {
        type: 'input',
        name: 'telegramChatId',
        message: 'Telegram Chat ID:',
      },
    ]);
    telegramConfig = telegramAnswers;
  }

  const spinner = ora('Creating configuration files...').start();

  try {
    // Create secrets directory
    await mkdir(join(targetDir, 'secrets'), { recursive: true });

    // Create .env file
    const envContent = generateEnvFile({ ...answers, ...telegramConfig });
    await writeFile(join(targetDir, '.env'), envContent);

    // Create docker-compose file
    const dockerComposeContent = generateDockerCompose();
    await writeFile(join(targetDir, 'docker-compose.yml'), dockerComposeContent);

    spinner.succeed('Configuration files created');

    console.log(chalk.green('\n✅ Conductor initialized successfully!\n'));
    console.log(chalk.white('Next steps:'));
    console.log(chalk.gray('  1. Copy your GitHub App private key to: ') + chalk.cyan(answers.githubPrivateKeyPath));
    console.log(chalk.gray('  2. Start the database and Redis: ') + chalk.cyan('docker-compose up -d'));
    console.log(chalk.gray('  3. Run database migrations: ') + chalk.cyan('pnpm db:migrate'));
    console.log(chalk.gray('  4. Start Conductor: ') + chalk.cyan('conductor start'));
    console.log('');
  } catch (err) {
    spinner.fail('Failed to create configuration files');
    console.error(chalk.red(err instanceof Error ? err.message : String(err)));
    process.exit(1);
  }
}

function generateEnvFile(config: Record<string, string>): string {
  return `# Conductor Configuration
# Generated by conductor init

# GitHub App Settings
GITHUB_APP_ID=${config.githubAppId}
GITHUB_PRIVATE_KEY_PATH=${config.githubPrivateKeyPath}
GITHUB_WEBHOOK_SECRET=${config.githubWebhookSecret}

# Database
DATABASE_URL=${config.databaseUrl}

# Redis
REDIS_URL=${config.redisUrl}

# Server
PORT=${config.port}
NODE_ENV=production

# Workspaces
WORKSPACES_DIR=/tmp/conductor-workspaces

# Notifications
${config.telegramBotToken ? `TELEGRAM_BOT_TOKEN=${config.telegramBotToken}` : '# TELEGRAM_BOT_TOKEN='}
${config.telegramChatId ? `TELEGRAM_CHAT_ID=${config.telegramChatId}` : '# TELEGRAM_CHAT_ID='}

# Agent Settings
SUB_AGENT_MODEL=claude-sonnet-4-20250514
`;
}

function generateDockerCompose(): string {
  return `version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: conductor-postgres
    environment:
      POSTGRES_USER: conductor
      POSTGRES_PASSWORD: conductor
      POSTGRES_DB: conductor
    volumes:
      - conductor-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: conductor-redis
    ports:
      - "6379:6379"
    volumes:
      - conductor-redis-data:/data
    restart: unless-stopped

volumes:
  conductor-postgres-data:
  conductor-redis-data:
`;
}
