/**
 * Pull Request Creator
 *
 * Creates GitHub pull requests for completed tasks.
 */

import { eq } from 'drizzle-orm';
import type { Octokit } from '@octokit/rest';
import {
  createLogger,
  getDb,
  pullRequests,
  subtasks,
  parseRepoFullName,
} from '@conductor/core';
import type { Task } from '@conductor/core';

const logger = createLogger('pr-creator');

interface CreatePROptions {
  task: Task;
  octokit: Octokit;
}

interface CreatedPR {
  id: string;
  number: number;
  url: string;
  title: string;
}

export async function createPullRequest(
  options: CreatePROptions
): Promise<CreatedPR> {
  const { task, octokit } = options;
  const { owner, repo } = parseRepoFullName(task.repositoryFullName);
  const db = getDb();

  // Get all subtasks to summarize changes
  const taskSubtasks = await db
    .select()
    .from(subtasks)
    .where(eq(subtasks.taskId, task.id));

  // Generate PR body
  const body = generatePRBody(task, taskSubtasks);

  // Get default branch
  const { data: repoData } = await octokit.repos.get({ owner, repo });
  const baseBranch = repoData.default_branch;

  if (!task.branchName) {
    throw new Error('Task has no branch name');
  }

  logger.info(
    {
      taskId: task.id,
      branch: task.branchName,
      base: baseBranch,
    },
    'Creating pull request'
  );

  // Create the PR
  const { data: pr } = await octokit.pulls.create({
    owner,
    repo,
    title: `[Conductor] ${task.title}`,
    body,
    head: task.branchName,
    base: baseBranch,
  });

  // Add labels
  try {
    await octokit.issues.addLabels({
      owner,
      repo,
      issue_number: pr.number,
      labels: ['conductor', 'automated'],
    });
  } catch (err) {
    logger.warn({ err }, 'Failed to add labels to PR');
  }

  // Store PR in database
  const [prRecord] = await db
    .insert(pullRequests)
    .values({
      taskId: task.id,
      repositoryFullName: task.repositoryFullName,
      number: pr.number,
      title: pr.title,
      body: pr.body || '',
      branchName: task.branchName,
      headSha: pr.head.sha,
      url: pr.html_url,
      status: 'open',
    })
    .returning();

  logger.info(
    { prId: prRecord.id, prNumber: pr.number, prUrl: pr.html_url },
    'Pull request created'
  );

  return {
    id: prRecord.id,
    number: pr.number,
    url: pr.html_url,
    title: pr.title,
  };
}

function generatePRBody(
  task: Task,
  taskSubtasks: Array<{ title: string; subprojectPath: string; filesModified: string[] }>
): string {
  const subtaskList = taskSubtasks
    .map((s) => `- **${s.subprojectPath}**: ${s.title}`)
    .join('\n');

  const allFiles = taskSubtasks.flatMap((s) => s.filesModified || []);
  const uniqueFiles = [...new Set(allFiles)];
  const filesList =
    uniqueFiles.length > 0
      ? uniqueFiles.map((f) => `- \`${f}\``).join('\n')
      : '_No files modified_';

  return `
## Summary

${task.description || task.title}

## Changes Made

This PR was automatically generated by **Conductor** to complete the following task from your GitHub Project.

### Subtasks Completed

${subtaskList}

### Files Modified

${filesList}

## How This Works

1. A task card was moved to the "Todo" column in your GitHub Project
2. Conductor's Master Agent analyzed the task and broke it into subtasks
3. Sub-Agents worked on each subtask in parallel
4. A Code Review Agent verified all changes
5. This PR was created for human review

## Review Checklist

- [ ] Code changes look correct
- [ ] Tests pass (check CI status)
- [ ] No security issues introduced
- [ ] Ready to merge

---

🤖 _This PR was created by [Conductor](https://github.com/your-org/conductor)_

Task ID: \`${task.id}\`
  `.trim();
}
